server:
  port: 8088

spring:
  application:
    name: springboot-exception
  profiles:
    active:
      - dev
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
