server:
  port: 7777

foo:
  list:
    - name: my name
      description: my description
    - name: arr1
      description: arr2
  remote-address: 192.168.1.1
  security:
    username: foo
    password: pwd
    roles:
      - USER
      - ADMIN
      - A
      - b
      - D
