server:
  port: 8888

spring:
  profiles:
    active:
      - test
  mvc:
    date-format:
      yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com:
      example:
        debug

foo:
  list:
    - name: my name
      description: my description
    - name: arr1
      description: arr2
  remote-address: 192.168.1.1
  security:
    username: foo
    password: pwd
    roles:
      - USER
      - ADMIN
      - A
      - b
      - D
