server:
  port: 8002
  tomcat:
    accesslog:
      enabled: true
      #directory: D:/data/microservices/tomcat/provider-bar

spring:
  mvc:
    dateFormat: yyyy-MM-dd HH:mm:ss
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://node3:3306/mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 5000
      pool-name: HikariCP
      connection-test-query: SELECT 1

mybatis:
  typeAliasesPackage: cn.kd.entity
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    defaultStatementTimeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


